import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { Entry } from '@/types/entry'
import {
  ms, fmtHrs, fmtDT, hobbsFlightTime, parseHobbs, compute, countRestDaysInWindow,
} from '@/lib/calculations'
import { utcToLocalParts } from '@/lib/timezone'

export type LogDetail = 'summary' | 'full' | 'both'

const DISCLAIMER =
  'This report is for reference and record-keeping only. Always verify compliance with your OpSpec, POI, and company manual. Generated by FAR 135.267 Duty & Flight Time Tracker.'

type SpanCell = { content: string; colSpan: number; styles?: { halign: 'left' } }

function entryLocalDate(e: Entry, tz?: string): string {
  if (!e.showTime) return ''
  if (e.showTime.endsWith('Z') && tz) return utcToLocalParts(e.showTime, tz)?.date ?? e.showTime.slice(0, 10)
  return e.showTime.split('T')[0] ?? ''
}

function fmtTime(dt: string, tz?: string): string {
  if (!dt) return '—'
  if (dt.endsWith('Z') && tz) return utcToLocalParts(dt, tz)?.time ?? dt.slice(11, 16)
  return dt.slice(11, 16) || '—'
}

function finalY(doc: jsPDF): number {
  return (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY
}

function baseTableOpts(margin: number, fontSize: number) {
  return {
    theme: 'grid' as const,
    styles: { fontSize, textColor: 0, lineColor: 0 },
    headStyles: { fillColor: 255, textColor: 0, fontStyle: 'bold' as const, lineColor: 0 },
    margin: { left: margin, right: margin },
  }
}

function periodStats(period: Entry[], periodStart: number, periodEnd: number, tz?: string) {
  const restDays = period.reduce((sum, e) => sum + countRestDaysInWindow(e, periodStart, periodEnd, tz), 0)
  const part135Flight = period
    .filter(e => !e.restDay && !e.part91)
    .reduce((sum, e) => sum + (hobbsFlightTime(parseHobbs(e.offBlocks), parseHobbs(e.onBlocks)) ?? 0), 0)
  return { restDays, part135Flight }
}

interface ReportData {
  periodEntries: Entry[]
  periodStart: number
  periodEnd: number
  periodLabel: string
  heading: string
  periodNoun: string
  restDays: number
  extraScorecard: [string, string][]
  restDayStatLabel: (restDays: number) => string
  isOverallOk: (violations: number, restDays: number) => boolean
}

function buildData(
  allEntries: Entry[],
  d: ReportData,
  tz: string | undefined,
): {
  statusText: string
  failDetail: string
  part135Legs: Entry[]
  part91Legs: Entry[]
  totalFlight: number
  totalViolations: number
  scRows: [string, string][]
  violations: { date: string; type: string; detail: string }[]
  exceedances: { date: string; route: string; over: string; reason: string; reqRest: number }[]
  sorted: Entry[]
  computed: Map<string, ReturnType<typeof compute>>
  dayMap: Map<string, { p135: number; p91: number; showTime: string; releaseTime: string; hasViolation: boolean }>
  restDayInfo: Map<string, { startStr: string; endStr: string; days: number }>
} {
  const { periodEntries, periodStart, periodEnd, restDays } = d
  const flightLegs  = periodEntries.filter(e => !e.restDay)
  const part135Legs = flightLegs.filter(e => !e.part91)
  const part91Legs  = flightLegs.filter(e => e.part91)

  const computed = new Map(flightLegs.map(e => [e.id, compute(e, allEntries, tz)]))

  let totalFlight = 0
  let flightFailCount = 0, dutyFailCount = 0, restFailCount = 0
  const violations: { date: string; type: string; detail: string }[] = []
  const exceedances: { date: string; route: string; over: string; reason: string; reqRest: number }[] = []

  for (const e of flightLegs) {
    const c = computed.get(e.id)!
    totalFlight += c.legFlight || 0
    if (e.part91) continue
    if (c.flightOk === false) { flightFailCount++; violations.push({ date: fmtDT(e.releaseTime || e.showTime), type: 'Flight Time Exceeded', detail: `Rolling 24-hr: ${fmtHrs(c.rolling24)} (limit ${c.maxFlight}h)` }) }
    if (c.dutyOk  === false) { dutyFailCount++;   violations.push({ date: fmtDT(e.showTime),                  type: 'Duty Period Exceeded',   detail: `Duty: ${fmtHrs(c.dutyPeriod)} (limit 14h)` }) }
    if (c.restOk  === false) { restFailCount++;   violations.push({ date: fmtDT(e.restStart),                 type: 'Rest Deficient',          detail: `Got ${fmtHrs(c.consRest)}, required ${c.reqRest}h` }) }
    if (c.excAmt > 0) exceedances.push({ date: fmtDT(e.releaseTime || e.showTime), route: `${(e.dep || '?').toUpperCase()}-${(e.arr || '?').toUpperCase()}`, over: fmtHrs(c.excAmt), reason: e.reason || '—', reqRest: c.reqRest })
  }

  const totalViolations = flightFailCount + dutyFailCount + restFailCount
  const overallOk  = d.isOverallOk(totalViolations, restDays)
  const statusText = overallOk ? 'COMPLIANT' : 'REVIEW REQUIRED'
  const failDetail = !overallOk ? ` — ${totalViolations} violation(s)${!d.isOverallOk(0, restDays) ? ' and/or rest day shortfall' : ''} detected` : ''

  const scRows: [string, string][] = [
    ['Rolling 24-hr Flight Time', flightFailCount === 0 ? 'PASS' : `${flightFailCount} VIOLATION(S)`],
    ['14-Hour Duty Day Limit',    dutyFailCount   === 0 ? 'PASS' : `${dutyFailCount} VIOLATION(S)`],
    ['Rest Requirements',         restFailCount   === 0 ? 'PASS' : `${restFailCount} DEFICIENCY(IES)`],
    ['10-hr Look-Back Rest',      'See detail rows below'],
    ...d.extraScorecard,
  ]

  const sorted = [...periodEntries].sort((a, b) => (ms(a.showTime) ?? 0) - (ms(b.showTime) ?? 0))

  const dayMap = new Map<string, { p135: number; p91: number; showTime: string; releaseTime: string; hasViolation: boolean }>()
  for (const e of periodEntries) {
    if (e.restDay) continue
    const dk = entryLocalDate(e, tz)
    if (!dk) continue
    if (!dayMap.has(dk)) dayMap.set(dk, { p135: 0, p91: 0, showTime: e.showTime ?? '', releaseTime: e.releaseTime ?? '', hasViolation: false })
    const dd = dayMap.get(dk)!
    if (e.releaseTime && e.releaseTime > dd.releaseTime) dd.releaseTime = e.releaseTime
    const ft = hobbsFlightTime(parseHobbs(e.offBlocks), parseHobbs(e.onBlocks)) ?? 0
    if (e.part91) { dd.p91 += ft } else {
      dd.p135 += ft
      const c = computed.get(e.id)!
      if (c.flightOk === false || c.dutyOk === false || c.restOk === false) dd.hasViolation = true
    }
  }

  const restDayInfo = new Map<string, { startStr: string; endStr: string; days: number }>()
  for (const e of periodEntries) {
    if (!e.restDay) continue
    const startStr = entryLocalDate(e, tz)
    const endStr = e.restDayEnd || startStr
    const days = countRestDaysInWindow(e, periodStart, periodEnd, tz)
    restDayInfo.set(e.id, { startStr, endStr, days })
  }

  return {
    statusText, failDetail, part135Legs, part91Legs, totalFlight,
    totalViolations, scRows, violations, exceedances, sorted, computed, dayMap, restDayInfo,
  }
}

function renderPDF(allEntries: Entry[], d: ReportData, tz: string | undefined, entity: string | undefined, logDetail: LogDetail): jsPDF {
  const r = buildData(allEntries, d, tz)
  const doc = new jsPDF({ orientation: logDetail === 'full' ? 'landscape' : 'portrait', unit: 'pt', format: 'letter' })

  const generated = new Date().toLocaleString('en-US', { dateStyle: 'long', timeStyle: 'short' })
  const margin = 40
  let y = margin

  function wrappedText(text: string, size: number) {
    doc.setFontSize(size)
    const width = doc.internal.pageSize.getWidth() - margin * 2
    const lines = doc.splitTextToSize(text, width) as string[]
    doc.text(lines, margin, y)
    y += 16 * lines.length
  }

  function header() {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(14)
    doc.text(`FAR 135.267 ${d.heading}`, margin, y)
    y += 18
    doc.setFont('helvetica', 'normal')
    wrappedText(`Period: ${d.periodLabel}   |   Entity: ${entity ?? 'All Entities'}   |   Generated: ${generated}`, 9)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.text(`Overall Status: ${r.statusText}${r.failDetail}`, margin, y)
    y += 18
    doc.setFont('helvetica', 'normal')
    const statLine = [
      `Part 135 Legs: ${r.part135Legs.length}${r.part91Legs.length ? ` (+${r.part91Legs.length} Part 91)` : ''}`,
      `Total Flight Time: ${fmtHrs(r.totalFlight)}`,
      `24-hr Rest Days: ${d.restDayStatLabel(d.restDays)}`,
      `Total Violations: ${r.totalViolations}`,
    ].join('   |   ')
    wrappedText(statLine, 9)
  }

  // Ensures a section heading never lands separated from the table that follows it —
  // autoTable paginates itself when a table doesn't fit, but a plain doc.text() heading has no such check.
  function sectionHeading(text: string, size = 10) {
    const pageHeight = doc.internal.pageSize.getHeight()
    if (y + 60 > pageHeight - margin) {
      doc.addPage()
      y = margin
    }
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(size)
    doc.text(text, margin, y)
    y += 4
  }

  header()

  sectionHeading('Scorecard')
  autoTable(doc, {
    startY: y,
    head: [['Requirement', 'Result']],
    body: r.scRows,
    ...baseTableOpts(margin, 8),
  })
  y = finalY(doc) + 14

  sectionHeading('Violations Detail')
  autoTable(doc, {
    startY: y,
    head: [['Date', 'Type', 'Detail']],
    body: r.violations.length ? r.violations.map(v => [v.date, v.type, v.detail]) : [[{ content: `No violations recorded this ${d.periodNoun}.`, colSpan: 3 }]],
    ...baseTableOpts(margin, 8),
  })
  y = finalY(doc) + 14

  sectionHeading('Exceedances')
  autoTable(doc, {
    startY: y,
    head: [['Date', 'Route', 'Over Limit', 'Reason', 'Req Rest']],
    body: r.exceedances.length
      ? r.exceedances.map(x => [x.date, x.route, x.over, x.reason, `${x.reqRest}h`])
      : [[{ content: `No exceedances this ${d.periodNoun}.`, colSpan: 5 }]],
    ...baseTableOpts(margin, 8),
  })
  y = finalY(doc) + 14

  function summaryLogBody(): (string | SpanCell)[][] {
    const seenDates = new Set<string>()
    const rows: (string | SpanCell)[][] = []
    for (const e of r.sorted) {
      if (e.restDay) {
        const { startStr, endStr, days } = r.restDayInfo.get(e.id)!
        const dateCell = endStr && endStr !== startStr ? `${startStr} - ${endStr}` : startStr
        rows.push([dateCell, { content: `REST DAY${days > 1 ? `S (${days} days)` : ''}`, colSpan: 5, styles: { halign: 'left' } }])
        continue
      }
      const dk = entryLocalDate(e, tz)
      if (!dk || seenDates.has(dk)) continue
      seenDates.add(dk)
      const dd = r.dayMap.get(dk)
      if (!dd) continue
      rows.push([dk, fmtTime(dd.showTime, tz), fmtTime(dd.releaseTime, tz), dd.p135 > 0 ? fmtHrs(dd.p135) : '—', dd.p91 > 0 ? fmtHrs(dd.p91) : '—', dd.hasViolation ? 'VIOLATION' : 'OK'])
    }
    return rows
  }

  function fullLogBody(): (string | SpanCell)[][] {
    const rows: (string | SpanCell)[][] = []
    for (const e of r.sorted) {
      if (e.restDay) {
        const { startStr, endStr, days } = r.restDayInfo.get(e.id)!
        const label = endStr && endStr !== startStr ? `24-HOUR REST DAYS: ${startStr} - ${endStr} (${days} days)` : '24-HOUR REST DAY'
        rows.push([fmtDT(e.showTime), { content: label, colSpan: 12, styles: { halign: 'left' } }])
        continue
      }
      const c = r.computed.get(e.id)!
      if (e.part91) {
        rows.push([
          fmtDT(e.showTime), e.crew === 'D' ? 'Dual' : 'Single',
          `${(e.dep || '—').toUpperCase()}-${(e.arr || '—').toUpperCase()}`,
          e.offBlocks || '—', e.onBlocks || '—', fmtHrs(c.legFlight),
          { content: 'Part 91 — Excluded from Sec. 135.267 limits', colSpan: 7, styles: { halign: 'left' as const } },
        ])
        continue
      }
      rows.push([
        fmtDT(e.showTime), e.crew === 'D' ? 'Dual' : 'Single',
        `${(e.dep || '—').toUpperCase()}-${(e.arr || '—').toUpperCase()}`,
        e.offBlocks || '—', e.onBlocks || '—', fmtHrs(c.legFlight),
        c.rolling24 !== null ? `${fmtHrs(c.rolling24)} / ${c.maxFlight}h` : '—',
        c.flightOk === null ? 'N/A' : c.flightOk ? 'OK' : 'EXCEEDED',
        fmtHrs(c.dutyPeriod),
        c.dutyOk === null ? 'N/A' : c.dutyOk ? 'OK' : 'EXCEEDED',
        `${fmtHrs(c.consRest)} / ${c.reqRest}h`,
        c.restOk === null ? 'N/A' : c.restOk ? 'OK' : 'DEFICIENT',
        c.excAmt > 0 ? fmtHrs(c.excAmt) : '—',
      ])
    }
    return rows
  }

  function drawSummaryLog() {
    sectionHeading('Flight Log (Summary)')
    autoTable(doc, {
      startY: y,
      head: [['Date', 'Show Time', 'Release Time', 'Pt.135 Time', 'Pt.91 Time', 'Status']],
      body: summaryLogBody(),
      ...baseTableOpts(margin, 8),
    })
    y = finalY(doc) + 14
  }

  function drawFullLog() {
    sectionHeading('Flight Log (Full Detail)')
    autoTable(doc, {
      startY: y,
      head: [['Show Time', 'Crew', 'Route', 'Off Blocks', 'On Blocks', 'Leg Time', 'Rolling 24-hr', 'Flt', 'Duty', 'Duty OK', 'Rest After', 'Rest OK', 'Exc']],
      body: fullLogBody(),
      ...baseTableOpts(margin, 7),
    })
    y = finalY(doc) + 14
  }

  if (logDetail === 'summary') {
    drawSummaryLog()
  } else if (logDetail === 'full') {
    drawFullLog()
  } else {
    drawSummaryLog()
    doc.addPage('letter', 'l')
    y = margin
    header()
    drawFullLog()
  }

  doc.setFontSize(7)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(90)
  const pageWidth = doc.internal.pageSize.getWidth()
  const lines = doc.splitTextToSize(DISCLAIMER, pageWidth - margin * 2)
  doc.text(lines, margin, doc.internal.pageSize.getHeight() - margin / 2)
  doc.setTextColor(0)

  return doc
}

function filenameFor(label: string, entity: string | undefined): string {
  const entityPart = (entity ?? 'ALL').replace(/\s+/g, '_')
  return `${label}-${entityPart}.pdf`
}

export function generateQuarterlyReportPDF(
  entries: Entry[], qIdx: number, year: number, tz?: string, entity?: string, logDetail: LogDetail = 'summary',
): boolean {
  const qStart = new Date(year, qIdx * 3, 1).getTime()
  const qEnd   = new Date(year, qIdx * 3 + 3, 1).getTime()
  const qLabel = ['Q1 (Jan–Mar)', 'Q2 (Apr–Jun)', 'Q3 (Jul–Sep)', 'Q4 (Oct–Dec)'][qIdx]
  const scoped = entity ? entries.filter(e => e.restDay || e.entity === entity) : entries
  const period = scoped.filter(e => { const a = ms(e.releaseTime) ?? ms(e.showTime); return a !== null && a >= qStart && a < qEnd })
  if (!period.length) return false

  const { restDays, part135Flight } = periodStats(period, qStart, qEnd, tz)

  const doc = renderPDF(entries, {
    periodEntries: period, periodStart: qStart, periodEnd: qEnd,
    periodLabel: `${qLabel} ${year}`, heading: 'Quarterly Compliance Report', periodNoun: 'quarter',
    restDays,
    extraScorecard: [
      ['24-hr Rest Days (>=13/qtr)', `${restDays} of 13 required`],
      ['Quarterly Flight Hours Sec. 135.267(a)', part135Flight < 500 ? `${fmtHrs(part135Flight)} of 500h — OK` : `${fmtHrs(part135Flight)} — EXCEEDED`],
    ],
    restDayStatLabel: rd => `${rd} / 13`,
    isOverallOk: (v, rd) => v === 0 && rd >= 13,
  }, tz, entity, logDetail)

  const qNum = `${year}-Q${qIdx + 1}`
  doc.save(filenameFor(qNum, entity))
  return true
}

export function generateMonthlyReportPDF(
  entries: Entry[], monthIdx: number, year: number, tz?: string, entity?: string, logDetail: LogDetail = 'summary',
): boolean {
  const mStart = new Date(year, monthIdx, 1).getTime()
  const mEnd   = new Date(year, monthIdx + 1, 1).getTime()
  const mLabel = `${'January February March April May June July August September October November December'.split(' ')[monthIdx]} ${year}`
  const scoped = entity ? entries.filter(e => e.restDay || e.entity === entity) : entries
  const period = scoped.filter(e => { const a = ms(e.releaseTime) ?? ms(e.showTime); return a !== null && a >= mStart && a < mEnd })
  if (!period.length) return false

  const { restDays, part135Flight } = periodStats(period, mStart, mEnd, tz)

  const doc = renderPDF(entries, {
    periodEntries: period, periodStart: mStart, periodEnd: mEnd,
    periodLabel: mLabel, heading: 'Monthly Compliance Report', periodNoun: 'month',
    restDays,
    extraScorecard: [
      ['24-hr Rest Days This Month', `${restDays} day${restDays !== 1 ? 's' : ''} (>=13/quarter required)`],
      ['Part 135 Flight Hours (Month)', fmtHrs(part135Flight)],
    ],
    restDayStatLabel: rd => `${rd}`,
    isOverallOk: v => v === 0,
  }, tz, entity, logDetail)

  const mNum = `${year}-${String(monthIdx + 1).padStart(2, '0')}`
  doc.save(filenameFor(mNum, entity))
  return true
}
